version: '2'
services:
  config:
    image: nginx
    volumes:
      - ./config:/usr/share/nginx/html:ro

  buildbot:
    image: buildbot/buildbot-master:master
    env_file:
        - db.env
    environment:
        - BUILDBOT_CONFIG_DIR=config
        - BUILDBOT_CONFIG_URL=http://config/master.cfg
        - BUILDBOT_WORKER_PORT=9989
        - BUILDBOT_WEB_URL=http://localhost:8080/
        - BUILDBOT_WEB_PORT=8080
    links:
      - config:config
      - db
    depends_on:
      - config:config
      - db
    ports:
      - "8080:8080"
  db:
    env_file:
        - db.env
    image: "postgres:9.4"
    expose:
        - 5432

  worker:
    image: "buildbot/buildbot-worker:master"
    environment:
        BUILDMASTER: buildbot
        BUILDMASTER_PORT: 9989
        WORKERNAME: example-worker
        WORKERPASS: pass
        WORKER_ENVIRONMENT_BLACKLIST: DOCKER_BUILDBOT* BUILDBOT_ENV_* BUILDBOT_1* WORKER_ENVIRONMENT_BLACKLIST

    links:
        - buildbot
